### PR TITLE
Add users, groups, group members query

### PR DESCRIPTION
**Pull request by developerworks**

### CODE REVIEW

**Comment by developerworks** [comment]
Seems like the pr includes commits last time merged, how to fix this ?

**Comment by developerworks** [comment]
Is there have a standard workflow about do a PR,  concrete git commands is better, thank you!

**Comment by herr-vogel** [comment]
@developerworks Thank you for you PR. Looks good. I will try to add the PR.

**Comment by hloydl** [comment]
Hi @developerworks 
I have added your changes with some adaption to the master branch. 

Cheers, Harald

**Pull request closed without merging**
