### PR TITLE
Add relationship process and activities

### PR DESCRIPTION
**Pull request by mmaico**
1 - The relationship between the historic process, activities and  incidents was created;
2 - Changed the H2 and commons version with vulnerability;
3 - Changed the documentation with the new settings.

@celanthe can you generate a new version of this lib? The artifact that must be sent to Maven Central is just the jar of the module extension.

thank you so much.

### CODE REVIEW

**Comment by celanthe** [comment]
@mmaico To clarify--Would you like me to merge the commits in this pull request and cut a new release version of this extension? Or would you like me to cut a new release before merging these commits? :) 

If you'd like, we have an automated release tool that can be implemented by adopting our [Camunda Community Action Parent POM](https://github.com/camunda-community-hub/community-hub-release-parent/blob/master/pom.xml) and [GitHub Actions Workflow](https://github.com/camunda-community-hub/community-action-maven-release). If you'd like to use this tooling I can add this repository to our infrastructure so it can inherit the necessary secrets to deploy releases to Maven Central.

**Comment by mmaico** [comment]
Hi @celanthe, i would like to merge this pull request before a new release. It would be great to have the automated release tool ;)
I will configure the project for automated deploy.

**Review by celanthe — APPROVED** [review]
Thank you for the many updates to this extension. All looks good to me! :)

**Comment by celanthe** [comment]
@mmaico I've merged this PR, and you should be able to cut the v0.4.0 release if you're ready to do so. If you'd like to try to utilize our automated tooling to do that instead of having to go through the process manually, I've already gone ahead and added this repository to our internal infrastructure tooling so you should be able to get up and running in short order! :)

**Pull request merged**
